### ISSUE TITLE
feature request: `aio app init --no-login` and required services

### ISSUE THREAD

**Issue by shazron** [adobe/aio-cli-plugin-app-templates#11]
## Description

For initializing an app, the developer may not be logged in and can install templates via `aio app init --no-login`. We need a way to output to the user what services are required for the app, as a notice, at the end of the initialization. The app plugin would then run this command to print this information.

## Suggestion
This can be an extension of the `info` command, or a separate command. This may be a plain text notice, json, or yaml.

```bash
$ aio templates required-services --json
{
  "@adobe/generator-app-asset-compute": ["AssetComputeSDK", "runtime"],
  "@adobe/generator-app-excshell": ["runtime"]
}
```

**Comment by irenelagno** [comment]
@slitviachenko , Correct me if I'm wrong, but this issue was resolved in the scope of https://jira.corp.adobe.com/browse/DEVX-2367. Can we close this issue as a fixed?

**Comment by slitviachenko** [comment]
@irenelagno , it looks like this issue is about printing some useful information why a template cannot be installed, for example, if an org doesn't have access to services specified in `install.yml`. https://jira.corp.adobe.com/browse/DEVX-2367 is about skipping configuring Console workspaces. So it is still relevant.

**Comment by irenelagno** [comment]
Internal ticket to address this issue: https://jira.corp.adobe.com/browse/DEVX-2502

**Comment by slitviachenko** [comment]
@shazron , could you please take a look at https://github.com/adobe/aio-cli-plugin-app-templates/pull/35 ?

**Comment by slitviachenko** [comment]
✅ https://github.com/adobe/aio-cli-plugin-app-templates/pull/35
