### ISSUE TITLE
aio templates install examples assume : is the topicSeparator

### ISSUE THREAD

**Issue by purplecabbage** [adobe/aio-cli-plugin-app-templates#28]
### Expected Behaviour
When published as part of the cli that uses ' ' as topicSeparator running `aio templates install --help` should output usable text.

### Actual Behaviour

```
ALIASES
  $ aio templates i

EXAMPLES
  $ aio templates:install https://github.com/org/repo

  $ aio templates:install git+https://github.com/org/repo

  $ aio templates:install ssh://github.com/org/repo

  $ aio templates:install git+ssh://github.com/org/repo
```

notice that ALIASES uses a `<space>` as the topicSeparator, but EXAMPLES uses `<colon>`
The examples will not be runnable if the user copy/pastes them to the command line

My suggestion is to just use spaces in the examples as that IS our standard.

**Comment by irenelagno** [comment]
Internal ticket to address issue https://jira.corp.adobe.com/browse/DEVX-2501

**Comment by AmyJZhao** [comment]
#32
