### ISSUE TITLE
migrate cli-ux (it has been deprecated)

### ISSUE THREAD

**Issue by shazron** [adobe/aio-cli-plugin-app-templates#30]
See https://github.com/oclif/core/tree/main/src/cli-ux

**Comment by irenelagno** [comment]
Internal ticket to address issue https://jira.corp.adobe.com/browse/DEVX-2500

**Comment by purplecabbage** [comment]
I believe this was covered here: https://github.com/adobe/aio-cli-plugin-app-templates/pull/8/files#diff-db1e6aa7b09b1b43ce34a9ffefc449ed500e95a964de30e616bb07db12199181

**Comment by slitviachenko** [comment]
✅ https://github.com/adobe/aio-cli-plugin-app-templates/pull/40
