### ISSUE TITLE
Aliases need some thought

### ISSUE THREAD

**Issue by purplecabbage** [adobe/aio-cli-plugin-app-templates#38]
Aliasing to a single char could cause issues, especially in a destructive operation like `remove|r`
I think `aio templates rm` would be a better choice.

`aio templates i|install` has a similar issue, but there is an expectation thanks to npm that `npm i` means `install`, and not `info` 

`aio template sub` instead of `s` for `submit`?
`un|uninstall` makes sense
`rollb|rollback`  ... meh, how often will this actually be used?

**Comment by slitviachenko** [comment]
@purplecabbage , so would it be better to remove aliases at all or choose >= 2 symbols for them ?

**Comment by purplecabbage** [comment]
I think a couple small changes would be enough:
- change `remove` alias `r` to be `rm` like the bash command
- remove `submit` alias `s` and `rollback` alias `rollb` 

Generally this plugin is expected to be run less frequently than say `aio app run` or `aio rt logs` so optimizing is less important, and might actually lead to more confusion ( and tech-debt ) out-weighing the convenience it offers (imho)

**Comment by slitviachenko** [comment]
@purplecabbage , ✅ addressed in https://github.com/adobe/aio-cli-plugin-app-templates/pull/42/commits/3b0c4522076ba0f80e54f6a9a42bd13b8d0ab110

**Comment by slitviachenko** [comment]
✅ https://github.com/adobe/aio-cli-plugin-app-templates/pull/42
