### ISSUE TITLE
Test coverage is < 100%

### ISSUE THREAD

**Issue by purplecabbage** [adobe/aio-cli-plugin-app-templates#9]
### Expected Behavior

100% of every line, branch, statement

core cli plugins include this in package.json
```
  "jest": {
    "collectCoverage": true,
    "rootDir": ".",
    "coverageThreshold": {
      "global": {
        "branches": 100,
        "lines": 100,
        "statements": 100
      }
    }
    ...
  }
```

**Comment by AmyJZhao** [comment]
https://github.com/adobe/aio-cli-plugin-app-templates/pull/12

Test coverage is now 100% on main @purplecabbage

**Comment by purplecabbage** [comment]
Nice! Closing this.
